export const product_options = [
  { value: "1", label: "detect_plus" },
  { value: "2", label: "detect" },
  { value: "3", label: "money" },
  { value: "4", label: "job" },
  { value: "5", label: "jobaddress" },
  { value: "6", label: "address" },
  { value: "7", label: "start" },
];

export const province = [
  { label: "AGRIGENTO", value: "AG", simpleValue: "agrigento" },
  { label: "ALESSANDRIA", value: "AL", simpleValue: "alessandria" },
  { label: "ANCONA", value: "AN", simpleValue: "ancona" },
  { label: "AOSTA", value: "AO", simpleValue: "aosta" },
  { label: "AREZZO", value: "AR", simpleValue: "arezzo" },
  { label: "ASCOLI PICENO", value: "AP", simpleValue: "ascolipiceno" },
  { label: "ASTI", value: "AT", simpleValue: "asti" },
  { label: "AVELLINO", value: "AV", simpleValue: "avellino" },
  { label: "BARI", value: "BA", simpleValue: "bari" },
  {
    label: "BARLETTA ANDRIA TRANI",
    value: "BT",
    simpleValue: "barlettaandriatrani",
  },
  { label: "BELLUNO", value: "BL", simpleValue: "belluno" },
  { label: "BENEVENTO", value: "BN", simpleValue: "benevento" },
  { label: "BERGAMO", value: "BG", simpleValue: "bergamo" },
  { label: "BIELLA", value: "BI", simpleValue: "biella" },
  { label: "BOLOGNA", value: "BO", simpleValue: "bologna" },
  { label: "BOLZANO", value: "BZ", simpleValue: "bolzano" },
  { label: "BRESCIA", value: "BS", simpleValue: "brescia" },
  { label: "BRINDISI", value: "BR", simpleValue: "brindisi" },
  { label: "CAGLIARI", value: "CA", simpleValue: "cagliari" },
  { label: "CALTANISSETTA", value: "CL", simpleValue: "caltanissetta" },
  { label: "CAMPOBASSO", value: "CB", simpleValue: "campobasso" },
  { label: "CARBONIA IGLESIAS", value: "CI", simpleValue: "carboniaiglesias" },
  { label: "CASERTA", value: "CE", simpleValue: "caserta" },
  { label: "CATANIA", value: "CT", simpleValue: "catania" },
  { label: "CATANZARO", value: "CZ", simpleValue: "catanzaro" },
  { label: "CHIETI", value: "CH", simpleValue: "chieti" },
  { label: "COMO", value: "CO", simpleValue: "como" },
  { label: "COSENZA", value: "CS", simpleValue: "cosenza" },
  { label: "CREMONA", value: "CR", simpleValue: "cremona" },
  { label: "CROTONE", value: "KR", simpleValue: "crotone" },
  { label: "CUNEO", value: "CN", simpleValue: "cuneo" },
  { label: "ENNA", value: "EN", simpleValue: "enna" },
  { label: "FERMO", value: "FM", simpleValue: "fermo" },
  { label: "FERRARA", value: "FE", simpleValue: "ferrara" },
  { label: "FIRENZE", value: "FI", simpleValue: "firenze" },
  { label: "FOGGIA", value: "FG", simpleValue: "foggia" },
  { label: "FORLI' CESENA", value: "FC", simpleValue: "forlicesena" },
  { label: "FROSINONE", value: "FR", simpleValue: "frosinone" },
  { label: "GENOVA", value: "GE", simpleValue: "genova" },
  { label: "GORIZIA", value: "GO", simpleValue: "gorizia" },
  { label: "GROSSETO", value: "GR", simpleValue: "grosseto" },
  { label: "IMPERIA", value: "IM", simpleValue: "imperia" },
  { label: "ISERNIA", value: "IS", simpleValue: "isernia" },
  { label: "LASPEZIA", value: "SP", simpleValue: "laspezia" },
  { label: "LAQUILA", value: "AQ", simpleValue: "laquila" },
  { label: "LATINA", value: "LT", simpleValue: "latina" },
  { label: "LECCE", value: "LE", simpleValue: "lecce" },
  { label: "LECCO", value: "LC", simpleValue: "lecco" },
  { label: "LIVORNO", value: "LI", simpleValue: "livorno" },
  { label: "LODI", value: "LO", simpleValue: "lodi" },
  { label: "LUCCA", value: "LU", simpleValue: "lucca" },
  { label: "MACERATA", value: "MC", simpleValue: "macerata" },
  { label: "MANTOVA", value: "MN", simpleValue: "mantova" },
  { label: "MASSA CARRARA", value: "MS", simpleValue: "massacarrara" },
  { label: "MATERA", value: "MT", simpleValue: "matera" },
  { label: "MEDIO CAMPIDANO", value: "VS", simpleValue: "mediocampidano" },
  { label: "MESSINA", value: "ME", simpleValue: "messina" },
  { label: "MILANO", value: "MI", simpleValue: "milano" },
  { label: "MODENA", value: "MO", simpleValue: "modena" },
  { label: "MONZA E BRIANZA", value: "MB", simpleValue: "monzaebrianza" },
  { label: "NAPOLI", value: "NA", simpleValue: "napoli" },
  { label: "NOVARA", value: "NO", simpleValue: "novara" },
  { label: "NUORO", value: "NU", simpleValue: "nuoro" },
  { label: "OGLIASTRA", value: "OG", simpleValue: "ogliastra" },
  { label: "OLBIA TEMPIO", value: "OT", simpleValue: "olbiatempio" },
  { label: "ORISTANO", value: "OR", simpleValue: "oristano" },
  { label: "PADOVA", value: "PD", simpleValue: "padova" },
  { label: "PALERMO", value: "PA", simpleValue: "palermo" },
  { label: "PARMA", value: "PR", simpleValue: "parma" },
  { label: "PAVIA", value: "PV", simpleValue: "pavia" },
  { label: "PERUGIA", value: "PG", simpleValue: "perugia" },
  { label: "PESARO E URBINO", value: "PU", simpleValue: "persaroeurbino" },
  { label: "PESCARA", value: "PE", simpleValue: "pescara" },
  { label: "PIACENZA", value: "PC", simpleValue: "piacenza" },
  { label: "PISA", value: "PI", simpleValue: "pisa" },
  { label: "PISTOIA", value: "PT", simpleValue: "pistoia" },
  { label: "PORDENONE", value: "PN", simpleValue: "pordenone" },
  { label: "POTENZA", value: "PZ", simpleValue: "potenza" },
  { label: "PRATO", value: "PO", simpleValue: "prato" },
  { label: "RAGUSA", value: "RG", simpleValue: "ragusa" },
  { label: "RAVENNA", value: "RA", simpleValue: "ravenna" },
  { label: "REGGIO CALABRIA", value: "RC", simpleValue: "reggiocalabria" },
  { label: "REGGIO EMILIA", value: "RE", simpleValue: "reggioemilia" },
  { label: "RIETI", value: "RI", simpleValue: "rieti" },
  { label: "RIMINI", value: "RN", simpleValue: "rimini" },
  { label: "ROMA", value: "RM", simpleValue: "roma" },
  { label: "ROVIGO", value: "RO", simpleValue: "rovigo" },
  { label: "SALERNO", value: "SA", simpleValue: "salerno" },
  { label: "SASSARI", value: "SS", simpleValue: "sassari" },
  { label: "SAVONA", value: "SV", simpleValue: "savona" },
  { label: "SIENA", value: "SI", simpleValue: "siena" },
  { label: "SIRACUSA", value: "SR", simpleValue: "siracusa" },
  { label: "SONDRIO", value: "SO", simpleValue: "sondrio" },
  { label: "TARANTO", value: "TA", simpleValue: "taranto" },
  { label: "TERAMO", value: "TE", simpleValue: "teramo" },
  { label: "TERNI", value: "TR", simpleValue: "terni" },
  { label: "TORINO", value: "TO", simpleValue: "torino" },
  { label: "TRAPANI", value: "TP", simpleValue: "trapani" },
  { label: "TRENTO", value: "TN", simpleValue: "trento" },
  { label: "TREVISO", value: "TV", simpleValue: "treviso" },
  { label: "TRIESTE", value: "TS", simpleValue: "trieste" },
  { label: "UDINE", value: "UD", simpleValue: "udine" },
  { label: "VARESE", value: "VA", simpleValue: "varese" },
  { label: "VENEZIA", value: "VE", simpleValue: "venezia" },
  {
    label: "VERBANO CUSIO OSSOLA",
    value: "VB",
    simpleValue: "verbanocusioossola",
  },
  { label: "VERCELLI", value: "VC", simpleValue: "vercelli" },
  { label: "VERONA", value: "VR", simpleValue: "verona" },
  { label: "VIBO VALENTIA", value: "VV", simpleValue: "vibovalentia" },
  { label: "VICENZA", value: "VI", simpleValue: "vicenza" },
  { label: "VITERBO", value: "VT", simpleValue: "viterbo" },
];
