import gugupa from "../../assets/gugupa.jpg";
import susanna from "../../assets/susanna.jpg";
import chiara from "../../assets/chiara.jpg";
import giulia from "../../assets/giulia_eredia.jpg";
import deborah from "../../assets/deborah.jpg";

const statusColorMap = {
  Evasa: "success",
  InLavorazione: "warning",
  InScadenza: "danger",
};

const INITIAL_VISIBLE_COLUMNS = [
  "id",
  "email",
  "name",
  "status",
  "data_richiesta",
  "data_scadenza",
  "actions",
];

const columns = [
  { name: "ID", uid: "id", sortable: true },
  { name: "Prodotto", uid: "email" },

  { name: "Posizioni", uid: "age", sortable: true },
  { name: "Cliente", uid: "role", sortable: true },
  { name: "Operatore", uid: "name", sortable: true },
  { name: "Responsabile", uid: "team" },

  { name: "Stato", uid: "status", sortable: true },

  { name: "Richiesta", uid: "data_richiesta", sortable: true },
  { name: "Scadenza", uid: "data_scadenza" },

  { name: "Azioni", uid: "actions" },
  { name: "Ev.Format", uid: "formato_evasione" },
];

const statusOptions = [
  { name: "Evasa", uid: "Evasa" },
  { name: "InLavorazione", uid: "InLavorazione" },
  { name: "InScadenza", uid: "InScadenza" },
];

const users = [
  {
    id: 1,
    name: "Augusto P",
    role: "Axactor",
    team: "Deborah R",
    status: "Evasa",
    age: "29",
    avatar: gugupa,
    email: "BD ADDRESS",
    data_richiesta: "12/03/23",
    data_scadenza: "23/03/23",
    data_evasione: "",
    formato_evasione: "xls",
  },
  {
    id: 2,
    name: "Susanna D",
    role: "Ccollection",
    team: "Chiara C",
    status: "InLavorazione",
    age: "25",
    avatar: susanna,
    email: "BD LIGHT PLUS 2.0",
    data_richiesta: "16/09/23",
    data_scadenza: "29/09/23",
    data_evasione: "",
    formato_evasione: "xls",
  },
  {
    id: 3,
    name: "Chiara C",
    role: "Axactor",
    team: "Chiara C",
    status: "InScadenza",
    age: "22",
    avatar: chiara,
    email: "BD ADDRESS LIGHT PLUS 2.0",
    data_richiesta: "16/07/23",
    data_scadenza: "29/07/23",
    data_evasione: "",
    formato_evasione: "xls",
  },
  {
    id: 4,
    name: "Giulia E",
    role: "Ares",
    team: "Deborah R",
    status: "InLavorazione",
    age: "28",
    avatar: giulia,
    email: "BD ADDRESS LIGHT PLUS 2.0",
    data_richiesta: "22/03/23",
    data_scadenza: "01/04/23",
    data_evasione: "",
    formato_evasione: "xls",
  },
  {
    id: 5,
    name: "Deborah R",
    role: "Axactor",
    team: "Deborah R",
    status: "Evasa",
    age: "24",
    avatar: deborah,
    email: "DETECT PLUS",
    data_richiesta: "29/08/23",
    data_scadenza: "08/08/23",
    data_evasione: "",
    formato_evasione: "xls",
  },
  {
    id: 6,
    name: "Brian K",
    role: "Ares",
    team: "Chiara C",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "BD ADDRESS LIGHT PLUS 2.0",
    status: "Evasa",
    data_richiesta: "19/03/23",
    data_scadenza: "01/04/23",
    data_evasione: "",
    formato_evasione: "xls",
  },
  {
    id: 7,
    name: "Michael H",
    role: "Ccollection",
    team: "Chiara C",
    status: "InLavorazione",
    age: "27",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    email: "DETECT PLUS",
    data_richiesta: "28/10/23",
    data_scadenza: "11/11/23",
    data_evasione: "",
    formato_evasione: "xls",
  },
  {
    id: 8,
    name: "Samantha Brooks",
    role: "Axactor",
    team: "Produzione 1",
    status: "Evasa",
    age: "31",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    email: "DETECT LIGHT",
    data_richiesta: "04/01/23",
    data_scadenza: "22/01/23",
    data_evasione: "",
    formato_evasione: "xls",
  },
  {
    id: 9,
    name: "Frank Harrison",
    role: "Ares",
    team: "Produzione 2",
    status: "InScadenza",
    age: "33",
    avatar: "https://i.pravatar.cc/150?img=4",
    email: "DETECT PLUS",
    data_richiesta: "14/05/23",
    data_scadenza: "29/05/23",
    data_evasione: "",
    formato_evasione: "xls",
  },
  {
    id: 10,
    name: "Emma Adams",
    role: "Axactor",
    team: "Produzione 1",
    status: "Evasa",
    age: "35",
    avatar: "https://i.pravatar.cc/150?img=5",
    email: "DETECT PLUS",
    data_richiesta: "02/03/23",
    data_scadenza: "13/03/23",
    data_evasione: "",
    formato_evasione: "xls",
  },
  {
    id: 11,
    name: "Brandon Stevens",
    role: "Ccollection",
    team: "Produzione 2",
    status: "Evasa",
    age: "22",
    avatar: "https://i.pravatar.cc/150?img=8",
    email: "DETECT PLUS",
    data_richiesta: "02/01/23",
    data_scadenza: "14/01/23",
    data_evasione: "",
    formato_evasione: "xls",
  },
  {
    id: 12,
    name: "Megan Richards",
    role: "Ares",
    team: "Produzione 1",
    status: "InLavorazione",
    age: "28",
    avatar: "https://i.pravatar.cc/150?img=10",
    email: "DETECT PLUS",
    data_richiesta: "14/11/23",
    data_scadenza: "27/11/23",
    data_evasione: "",
    formato_evasione: "xls",
  },
  {
    id: 13,
    name: "Oliver Scott",
    role: "Axactor",
    team: "Produzione 2",
    status: "Evasa",
    age: "37",
    avatar: "https://i.users pravatar.cc/150?img=12",
    email: "DETECT PLUS",
    data_richiesta: "12/03/23",
    data_scadenza: "23/03/23",
    data_evasione: "",
    formato_evasione: "xls",
  },
  {
    id: 14,
    name: "Grace Allen",
    role: "Ccollection",
    team: "Produzione 2",
    status: "Evasa",
    age: "30",
    avatar: "https://i.pravatar.cc/150?img=16",
    email: "DETECT PLUS",
    data_richiesta: "01/06/23",
    data_scadenza: "12/07/23",
    data_evasione: "",
    formato_evasione: "xls",
  },
  {
    id: 15,
    name: "Noah Carter",
    role: "Ares",
    team: "Produzione 1",
    status: "InLavorazione",
    age: "31",
    avatar: "https://i.pravatar.cc/150?img=15",
    email: "DETECT PLUS",
    data_richiesta: "17/08/23",
    data_scadenza: "29/08/23",
    data_evasione: "",
    formato_evasione: "xls",
  },
  {
    id: 16,
    name: "Ava Perez",
    role: "Axactor",
    team: "Produzione 2",
    status: "Evasa",
    age: "29",
    avatar: "https://i.pravatar.cc/150?img=20",
    email: "DETECT PLUS",
    data_richiesta: "15/06/23",
    data_scadenza: "29/06/23",
    data_evasione: "",
    formato_evasione: "xls",
  },
  {
    id: 17,
    name: "Liam Johnson",
    role: "Ccollection",
    team: "Produzione 1",
    status: "Evasa",
    age: "28",
    avatar: "https://i.pravatar.cc/150?img=33",
    email: "DETECT PLUS",
    data_richiesta: "02/07/23",
    data_scadenza: "23/08/23",
    data_evasione: "",
    formato_evasione: "xls",
  },
  {
    id: 18,
    name: "Sophia Taylor",
    role: "Ccollection",
    team: "Produzione 1",
    status: "Evasa",
    age: "27",
    avatar: "https://i.pravatar.cc/150?img=29",
    email: "DETECT PLUS",
    data_richiesta: "13/04/23",
    data_scadenza: "23/04/23",
    data_evasione: "",
    formato_evasione: "xls",
  },
  {
    id: 19,
    name: "Lucas Harris",
    role: "Ccollection",
    team: "Produzione 2",
    status: "InLavorazione",
    age: "32",
    avatar: "https://i.pravatar.cc/150?img=50",
    email: "DETECT PLUS",
    data_richiesta: "12/05/23",
    data_scadenza: "23/05/23",
    data_evasione: "",
    formato_evasione: "xls",
  },
  {
    id: 20,
    name: "Mia Robinson",
    role: "Axactor",
    team: "Produzione 2",
    status: "Evasa",
    age: "26",
    avatar: "https://i.pravatar.cc/150?img=45",
    email: "DETECT PLUS",
    data_richiesta: "16/03/23",
    data_scadenza: "30/03/23",
    data_evasione: "",
    formato_evasione: "xls",
  },
];

export {
  users,
  columns,
  statusOptions,
  statusColorMap,
  INITIAL_VISIBLE_COLUMNS,
};
